FROM amazonlinux
RUN yum install java* -y
RUN yum install tar -y
ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz .
RUN tar -xzf /apache-tomcat-9.0.85.tar.gz -C /opt
COPY student.war /opt/apache-tomcat-9.0.85/webapps/
WORKDIR /opt/apache-tomcat-9.0.
CMD ["/opt/apache-tomcat-9.0.85/bin/catalina.sh","run"]
